version: '2'
services:
  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./angular-version:/var/lib/grafana/plugins/map-panel/
      #- .:/var/lib/grafana/plugins/oc-map-panel/
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  crate:
    image: crate:4.1.4
    ports:
      - "4200:4200"
      - "5432:5432"
    volumes:
      - crate-storage:/data
    environment:
      CRATE_HEAP_SIZE: 1g
    command: crate -Cnode.name=crate
volumes:
  grafana-storage:
  crate-storage:
