version: '2'
services:
  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - .:/var/lib/grafana/plugins/orchestracities-map-panel/
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  crate:
    image: crate:4.1.4
    ports:
      - "4200:4200"
    volumes:
      - crate-storage:/data
    environment:
      CRATE_HEAP_SIZE: 1g
    command: crate -Cnode.name=crate
  timescale:
    image: timescale/timescaledb-postgis:${TIMESCALE_VERSION:-1.7.1-pg12}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=*
    volumes:
      - timescale-storage:/data
      - ./db-init:/db-init
volumes:
  grafana-storage:
  crate-storage:
  timescale-storage:
