// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file


//const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
//module.exports = standard.jestConfig();


module.exports = {
    preset: 'ts-jest',
    verbose: false,
    moduleDirectories: [ 'node_modules', 'src' ],
    moduleFileExtensions: [ 'ts', 'tsx', 'js', 'jsx', 'json' ],
    setupFiles: [
      './node_modules/@grafana/toolkit/src/config/matchMedia.js',
      'jest-canvas-mock'
    ],
    globals: {
      'ts-jest': {
        isolatedModules: true,
        tsconfig: './tsconfig.json'
      }
    },
    coverageReporters: [ 'json-summary', 'text', 'lcov' ],
    collectCoverageFrom: [ 'src/**/*.{ts,tsx}', '!**/node_modules/**', '!**/vendor/**' ],
    reporters: [ 'default', [ 'jest-junit', [Object] ] ],
    testEnvironment: 'jest-environment-jsdom-fifteen',
    testMatch: [
      '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
      '<rootDir>/src/**/*.{spec,test,jest}.{js,jsx,ts,tsx}',
      '<rootDir>/spec/**/*.{spec,test,jest}.{js,jsx,ts,tsx}'
    ],
    transform: {
      "^.+\\.tsx?$": "ts-jest",
      "^.+\\.jsx?$": "babel-jest", // <- also compile js/x files
    },
    transformIgnorePatterns: [
      '[/\\\\\\\\]node_modules[/\\\\\\\\].+\\\\.(js|jsx|ts|tsx)$',
      '^.+\\\\.module\\\\.(css|sass|scss)$',
      'node_modules/(?!(ol)/)',
    ],
    moduleNameMapper: {
      '\\.(css|sass|scss)$': './node_modules/@grafana/toolkit/src/config/styles.mock.js',
    }
  }
